### ISSUE TITLE
Extension Setting On/Off "space after comma"

### ISSUE THREAD

**Issue by gorri1a** [uwidev/sd_extension-prompt_formatter#4]
Can turn off the space after the comma?
if  cannnot, glad to selectable in the extended settings.
When moving arrow keys in prompt editing, having space will increase the work.
A useful extension. thank you!

**Comment by uwidev** [comment]
You make a good point. I wonder though if this should be part of default behavior or just an option on the side. I think for now I'll have it as default behavior, as you said, to decrease the work. But if people really want to make their prompts all formal and pretty at the expense of more work, then they can do so.

I think the goal moving forward with this extension is to increase prompt workflow efficiency, with aesthetics still taken into account, but secondary.

**Comment by uwidev** [comment]
Done.

Also, be careful when you say "prompt editing" because I thought you meant [prompt editing](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#prompt-editing). I got what you mean, but maybe "when editing a prompt" or something like that in the future for better clarification. Though I think that prompt editing feature should be renamed though.

**Comment by gorri1a** [comment]
Thank you! Your quick work is excellent.

You are right, the comma space "," is necessary to make the prompt look pretty and not necessary when editing the prompt.

When looking at someone's prompt, the space might make it more readable.

I'm Japanese and use google translate, so I translated "prompt editting" in a strange way. I will be careful from now on, thank you.
